services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/DesarrolladorPijaosSalud/ecommerce
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: REDIS_HOST
        fromDatabase:
          name: laravel-redis
          property: host
      - key: REDIS_PORT
        fromDatabase:
          name: laravel-redis
          property: port

databases:
  - name: laravel-db
    plan: free
    databaseName: ecommerce
    user: root
  - name: laravel-redis
    plan: free
